const fSlider = [
    {
        id : "product1",
        image : '/amulbutter.jpg',
        mainHeading : 'Amul Butter',
        subHeading : 'Good For Health Specially for young age',
        MRP : 200,
        Deal : 80,
        name : 'product',
        price : 50,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
        width : '100px'
    },
    {
        id : "product2",
        image : '/garnier.jpg',
        mainHeading : 'Garnier',
        subHeading : 'Good For Garnier Specially for young age',
        MRP : 250,
        Deal : 180,
        name : 'product',
        price : 180,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product3",
        image : '/oil.jpg',
        mainHeading : 'Hair Oil',
        subHeading : 'Good Oil For Health Specially for young age',
        MRP : 120,
        Deal : 80,
        name : 'product',
        price : 80,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product4",
        image : '/garnier.jpg',
        mainHeading : 'Garnier Large',
        subHeading : 'Good For Garnier Specially for Long Term young age',
        MRP : 350,
        Deal : 280,
        name : 'product',
        price : 280,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product5",
        image : '/amulbutter.jpg',
        mainHeading : 'Amul Butter Large',
        subHeading : 'Good For Health Specially for Large age',
        MRP : 300,
        Deal : 180,
        name : 'product',
        price : 180,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
        width : '100px'
    },
    {
        id : "product6",
        image : '/garnier.jpg',
        mainHeading : 'Garnier SM',
        subHeading : 'Good For Garnier SM Specially for young age',
        MRP : 100,
        Deal : 60,
        name : 'product',
        price : 60,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product7",
        image : '/oil.jpg',
        mainHeading : 'Oil SM',
        subHeading : 'Good Oil SM For Health Specially for young age',
        MRP : 100,
        Deal : 70,
        name : 'product',
        price : 70,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product8",
        image : '/earbirds.jpg',
        mainHeading : 'EarBuds',
        subHeading : 'Good For Ears Specially for young age',
        MRP : 500,
        Deal : 420,
        name : 'product',
        price : 420,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
    },
    {
        id : "product9",
        image : '/macbook.jpg',
        mainHeading : 'Mackbook',
        subHeading : 'Good For Development Specially for young age',
        MRP : 1200,
        Deal : 1100,
        name : 'product',
        price : 1100,
        description : 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero magni ducimus modi! Sed fugiat consequuntur nulla expedita, a voluptates voluptate ipsa eveniet fuga ut, quae et vero ullam illo autem.',
        width : '100px',
    },
]

module.exports = fSlider;